package com.skybox.composeapitests.ui.theme

import androidx.compose.ui.graphics.Color

val testLightPrimary = Color(0xFF825500)
val testLightOnPrimary = Color(0xFFFFFFFF)
val testLightPrimaryContainer = Color(0xFFFFDDAE)
val testLightOnPrimaryContainer = Color(0xFF2A1800)
val testLightSecondary = Color(0xFF6F5B40)
val testLightOnSecondary = Color(0xFFFFFFFF)
val testLightSecondaryContainer = Color(0xFFFADEBC)
val testLightOnSecondaryContainer = Color(0xFF271904)
val testLightTertiary = Color(0xFF516440)
val testLightOnTertiary = Color(0xFFFFFFFF)
val testLightTertiaryContainer = Color(0xFFD3EABC)
val testLightOnTertiaryContainer = Color(0xFF102004)
val testLightError = Color(0xFFBA1B1B)
val testLightErrorContainer = Color(0xFFFFDAD4)
val testLightOnError = Color(0xFFFFFFFF)
val testLightOnErrorContainer = Color(0xFF410001)
val testLightBackground = Color(0xFFFCFCFC)
val testLightOnBackground = Color(0xFF1F1B16)
val testLightSurface = Color(0xFFFCFCFC)
val testLightOnSurface = Color(0xFF1F1B16)
val testLightSurfaceVariant = Color(0xFFF0E0CF)
val testLightOnSurfaceVariant = Color(0xFF4F4539)
val testLightOutline = Color(0xFF817567)
val testLightInverseOnSurface = Color(0xFFF9EFE6)
val testLightInverseSurface = Color(0xFF34302A)
val testLightPrimaryInverse = Color(0xFFFFB945)

val testDarkPrimary = Color(0xFFFFB945)
val testDarkOnPrimary = Color(0xFF452B00)
val testDarkPrimaryContainer = Color(0xFF624000)
val testDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val testDarkSecondary = Color(0xFFDDC3A2)
val testDarkOnSecondary = Color(0xFF3E2E16)
val testDarkSecondaryContainer = Color(0xFF56442B)
val testDarkOnSecondaryContainer = Color(0xFFFADEBC)
val testDarkTertiary = Color(0xFFB8CEA2)
val testDarkOnTertiary = Color(0xFF243516)
val testDarkTertiaryContainer = Color(0xFF3A4C2B)
val testDarkOnTertiaryContainer = Color(0xFFD3EABC)
val testDarkError = Color(0xFFFFB4A9)
val testDarkErrorContainer = Color(0xFF930006)
val testDarkOnError = Color(0xFF680003)
val testDarkOnErrorContainer = Color(0xFFFFDAD4)
val testDarkBackground = Color(0xFF1F1B16)
val testDarkOnBackground = Color(0xFFEAE1D9)
val testDarkSurface = Color(0xFF1F1B16)
val testDarkOnSurface = Color(0xFFEAE1D9)
val testDarkSurfaceVariant = Color(0xFF4F4539)
val testDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val testDarkOutline = Color(0xFF9C8F80)
val testDarkInverseOnSurface = Color(0xFF32281A)
val testDarkInverseSurface = Color(0xFFEAE1D9)
val testDarkPrimaryInverse = Color(0xFF624000)
